#!/bin/bash
# Root-side hand-off for 外部リンクドメイン生成 auto-TLS.
#
# Triggered by external-link-domain-cert-issue.path when the CRM JVM (running as
# centos, NoNewPrivileges=true, cannot sudo) stages a request file at
# /tmp/external-link-domain-cert-request.new — same privilege-boundary pattern as
# softbank-env-install (see deploy/systemd/README.md).
#
# Request file format: exactly one line, the bare domain to issue a cert for
# (e.g. "ep84ti.jp" — no scheme, no path, no port). Written by
# ExternalLinkDomainCertService.requestCertificate().
#
# Steps:
#   1. Validate the domain strictly (defense against injection via a malicious
#      admin-entered "domain" value reaching a root-run script).
#   2. certbot certonly --webroot (uses the shared /.well-known/acme-challenge/
#      location already present in every nginx vhost — see ops/nginx-crm.conf).
#   3. Write a templated HTTPS server block to
#      /etc/nginx/conf.d/external-link-domains/<domain>.conf.
#   4. nginx -t && systemctl reload nginx.
#
# Result is written back to /tmp/external-link-domain-cert-result.<domain> so the
# JVM can poll and show pending/success/failure in the settings UI.

set -euo pipefail

REQUEST_FILE="/tmp/external-link-domain-cert-request.new"
WEBROOT="/var/www/letsencrypt"
NGINX_DOMAIN_DIR="/etc/nginx/conf.d/external-link-domains"
CRM_BACKEND_UPSTREAM="crm_backend"

log() { echo "[certbot-issue-domain-cert] $*"; }

if [[ ! -f "$REQUEST_FILE" ]]; then
    log "no request file at $REQUEST_FILE — nothing to do"
    exit 0
fi

DOMAIN="$(head -1 "$REQUEST_FILE" | tr -d '[:space:]')"

# Strict validation: lowercase letters, digits, hyphens, dots only — a standard
# DNS hostname shape. Rejects anything that could break out of the certbot/nginx
# command context (shell metacharacters, path traversal, wildcards, etc.).
if [[ ! "$DOMAIN" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$ ]]; then
    log "REJECTED: '$DOMAIN' does not look like a valid hostname"
    echo "REJECTED_INVALID_DOMAIN" > "/tmp/external-link-domain-cert-result.invalid"
    rm -f "$REQUEST_FILE"
    exit 1
fi

RESULT_FILE="/tmp/external-link-domain-cert-result.${DOMAIN}"
log "processing domain=$DOMAIN"

mkdir -p "$WEBROOT/.well-known/acme-challenge"
# SELinux: nginx (httpd_t) can only read httpd_sys_content_t. The webroot's persistent
# fcontext policy is registered once via `semanage fcontext` (see deploy/systemd/README.md
# prerequisite step); this restorecon re-applies it to any freshly created challenge files
# certbot writes on this run, in case they land with the wrong default context.
if command -v restorecon >/dev/null 2>&1; then
    restorecon -R "$WEBROOT" || true
fi

if certbot certonly \
    --webroot -w "$WEBROOT" \
    -d "$DOMAIN" \
    --non-interactive --agree-tos \
    --register-unsafely-without-email \
    --keep-until-expiring \
    >> /var/log/letsencrypt/external-link-domain-cert.log 2>&1; then
    log "certbot issued/renewed cert for $DOMAIN"
else
    log "certbot FAILED for $DOMAIN — see /var/log/letsencrypt/external-link-domain-cert.log"
    echo "FAILED_CERTBOT" > "$RESULT_FILE"
    rm -f "$REQUEST_FILE"
    exit 1
fi

mkdir -p "$NGINX_DOMAIN_DIR"
CONF_FILE="$NGINX_DOMAIN_DIR/${DOMAIN}.conf"
TMP_CONF="$(mktemp)"

cat > "$TMP_CONF" <<NGINXCONF
# Auto-generated by certbot-issue-domain-cert.sh for ${DOMAIN} — do not hand-edit,
# regenerated on every (re-)issue.
server {
    listen 443 ssl http2;
    server_name ${DOMAIN};
    server_tokens off;

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Frame-Options           "SAMEORIGIN" always;
    add_header X-Content-Type-Options    "nosniff" always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin" always;

    client_max_body_size 20m;

    location ^~ /.well-known/acme-challenge/ {
        root ${WEBROOT};
        default_type "text/plain";
    }

    location / {
        proxy_pass              http://${CRM_BACKEND_UPSTREAM};
        proxy_http_version      1.1;
        proxy_set_header        Host              \$host;
        proxy_set_header        X-Real-IP         \$remote_addr;
        proxy_set_header        X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto \$scheme;
        proxy_connect_timeout   10s;
        proxy_send_timeout      30s;
        proxy_read_timeout      3600s;
    }
}
NGINXCONF

mv "$TMP_CONF" "$CONF_FILE"
chmod 0644 "$CONF_FILE"
# SELinux: `mv` from /tmp (tmp_t) does not relabel to the destination directory's context —
# nginx (httpd_t) needs httpd_config_t to read it. The persistent fcontext policy for this
# directory is registered once (see deploy/systemd/README.md prerequisite step); restorecon
# re-applies it to this specific file every run.
if command -v restorecon >/dev/null 2>&1; then
    restorecon "$CONF_FILE" || true
fi
log "wrote $CONF_FILE"

if nginx -t >> /var/log/letsencrypt/external-link-domain-cert.log 2>&1; then
    systemctl reload nginx
    log "nginx reloaded"
    echo "SUCCESS" > "$RESULT_FILE"
else
    log "nginx -t FAILED after writing $CONF_FILE — removing it and leaving the old config live"
    rm -f "$CONF_FILE"
    echo "FAILED_NGINX_CONFIG" > "$RESULT_FILE"
    rm -f "$REQUEST_FILE"
    exit 1
fi

rm -f "$REQUEST_FILE"
log "done: $DOMAIN"
